blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://your-documentation-url.com
    about: Read our comprehensive documentation.
  - name: â­ Sponsor MyPackage
    url: https://github.com/sponsors/MyPackage
    about: Help the continued development.
  - name: ğŸ’¬ Ask on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/MyPackage
    about: The best place for asking general purpose questions.
  - name: ğŸ’¬ Ask on YourSocialMediaChannel
    url: https://url-of-your-social-media-channel.com
    about: Get in touch with the whole community.
